export enum DriverTypes {
    GET_DRIVERS_REQUEST = 'driver/GET_DRIVERS_REQUEST',
    GET_DRIVERS_SUCCESS = 'driver/GET_DRIVER_SUCCESS',
    GET_DRIVERS_FAVORITES_REQUEST = 'driver/GET_DRIVERS_FAVORITES_REQUEST',
    GET_DRIVERS_FAVORITES_SUCCESS = 'driver/GET_DRIVERS_FAVORITES_SUCCESS',
}
