export enum PassengerTripsTypes {
    GET_PASSENGER_TRIPS_REQUEST = 'passengerTrip/GET_PASSENGER_TRIPS_REQUEST',
    GET_PASSENGER_TRIPS_SUCCESS = 'passengerTrip/GET_PASSENGER_TRIPS_SUCCESS',
    GET_PASSENGER_TRIPS_FINISHED_REQUEST = 'passengerTrip/GET_PASSENGER_TRIPS_FINISHED_REQUEST',
    GET_PASSENGER_TRIPS_FINISHED_SUCCESS = 'passengerTrip/GET_PASSENGER_TRIPS_FINISHED_SUCCESS',
}
